from pydantic import BaseModel, Field

class TransactionRequest(BaseModel):
    transaction_id: str = Field(..., description="Unique UUID generated by frontend")
    user_id: str = Field(..., description="Unique identifier for the user")
    # Abuse prevention: Restrict transaction size
    amount: float = Field(..., gt=0, le=10000, description="Amount must be between 0.01 and 10,000")

class UserSummaryResponse(BaseModel):
    user_id: str
    total_score: float
    transaction_count: int

    class Config:
        from_attributes = True